### ISSUE TITLE
Insufficient escaping in ThemedController (security issue)

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#113]
**escape()** feature within ThemedController should support contextual escaping. Developers who lack knowledge of XSS attacks might have a false sense of security relying on Sprint's **escape()**. Unfortunately, CodeIgniter doesn't provide contextual escaping by default (See [Common Functions](http://www.codeigniter.com/user_guide/general/common_functions.html) and [Security Best Practices](http://www.codeigniter.com/user_guide/general/security.html)). In fact, I think the way the Security Best Practices is written is a bit misleading. ... we should fix that within Sprint!

If you're not against borrowing from the Zend Framework, we should implement their [Escaper](http://framework.zend.com/manual/current/en/modules/zend.escaper.introduction.html) component. [Here's](https://github.com/zendframework/zf2/tree/0d24ccc86830f969e361169365c8b2cabe391bae/library/Zend/Escaper) the meat of the source code minus the helpers. The breadth of their escapers cover [Owasp's XSS Cheat Sheet](https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet) requirements.

[jquery-encoder](https://github.com/chrisisbeef/jquery-encoder) is a similar implementation written in Javascript.

**Comment by ronvillalon** [comment]
Correction: **escape()** should be **esc()**

I suggest we remove **esc()** implementation throughout the ThemedController and require Sprint developers to escape data based on context.

**Comment by ronvillalon** [comment]
Looks like this was mentioned a while back within the CodeIgniter community (bcit-ci/CodeIgniter/issues/470). Although it was rejected by CodeIgniter, I still think contextual escaping is very important. While I would agree that xss_clean is a great idea for making sure only clean data gets into the DB, I think this doesn't take into consideration when original content needs to be saved to the DB--in these situations, contextual escaping is a security MUST.

In addition to OWASP, if you've ever seen a XSS vulnerability found by WebInspect, they also highly recommend proper escaping:

> Cross-Site Scripting attacks can be avoided by carefully validating all input, and properly encoding all output. When validating user input, verify that it matches the strictest definition of valid input possible. For example, if a certain parameter is supposed to be a number, attempt to convert it to a numeric data type in your programming language.
> 
> PHP: intval("0".$_GET['q']);
> 
> The same applies to date and time values, or anything that can be converted to a stricter type before being used. When accepting other types of text input, make sure the value matches either a list of acceptable values (white-listing), or a strict regular expression. If at any point the value appears invalid, do not accept it. Also, do not attempt to return the value to the user in an error message.
> 
> Most server side scripting languages provide built in methods to convert the value of the input variable into correct, noninterpretable HTML. These should be used to sanitize all input before it is displayed to the client.
> 
> PHP: string htmlspecialchars (string string [, int quote_style])
> 
> When reflecting values into JavaScript or another format, make sure to use a type of encoding that is appropriate. Encoding data for HTML is not sufficient when it is reflected inside of a script or style sheet. For example, when reflecting data in a JavaScript string, make sure to encode all non-alphanumeric characters using hex (\xHH) encoding.
> 
> If you have JavaScript on your page that accesses unsafe information (like location.href) and writes it to the page (either with document.write, or by modifying a DOM element), make sure you encode data for HTML before writing it to the page. JavaScript does not have a built-in function to do this, but many frameworks do. If you are lacking an available function, something like the following will handle most cases:
> 
> s = s.replace(/&/g,'&').replace(/"/i,'"').replace(//i,'>').replace(/'/i,'&apos;')
> 
> Ensure that you are always using the right approach at the right time. Validating user input should be done as soon as it is received. Encoding data for display should be done immediately before displaying it.

.. I know I am referencing CodeIgniter code but given that the idea of including it in CodeIgniter's core was rejected, I hope you will consider it. That or remove the **esc()** since some developers may not know how to use it properly...

**Comment by lonnieezell** [comment]
> I suggest we remove esc() implementation throughout the ThemedController and require Sprint developers to escape data based on context.

While I agree with a lot of your points here, a number of the items in the OWASP checklist are taken care of with simple commands, already, like `urlencode`, `json_encode`, and CI's own `xss_clean` for javascript and CSS areas I believe, etc. And, yes, I know that xss_clean has it's own issues. :)

The `esc()` method is intended to be used solely within the HTML body, and the docs, while not explicitly stating it, do imply it is for that use. So, this would only cover OWASP's Rule 1, and that's all it was ever really intended for, though it does look like it would have been assumed to be usable on Rule 2, also. 

Reading through the ZF Escaper library, I do really like it. So, I'm going to move to include it and revamp the way the setVar method works with it, because I still think that auto-escaping of data is critical in the view to help developers have the best security out of the box. 

Thanks for bringing this stuff to my attention. Sounds like a great addition.

**Comment by lonnieezell** [comment]
This has been fixed in the latest commits. 

The solution I used was to allow contexts to be specified when using the `setVar` method, or when using the `esc()` function, which now uses ZF's escaper to handle the items based on context. So, we have better, more secure code (thanks!) while keep things simple to use and read, I hope.

**Comment by ronvillalon** [comment]
Awesome news!
