### ISSUE TITLE
Feature Requests etc: Testing tutorial? Book? SprintPHP vs Bonfire? 

### ISSUE THREAD

**Issue by ThinkALot** [ci-bonfire/Sprint#118]
The blog tutorial is good, and it worked for me. I didn't really understand what I was doing, but it still helped a lot. Thanks for making it.

Also, I read the help doc explaining how to test my code, but regardless, I don't understand how to do it. A detailed, step-by-step tutorial showing how to test would be useful.

I read somewhere that a CI 3 book is being written. When will it be available? Does it consist only of the existing help docs, or is there more? Can we buy the early chapters of the book, and download the rest as they become available?

In case you're wondering about readers' preferences: From my own perspective, I prefer books that assume the reader knows very little, and explain everything in detail. Also, I prefer books that show each procedure, then explain what's happening in the code, and also explain it on a deeper conceptual level when possible. In other words, I prefer books that explain both the procedure _and_ the concept, every step of the way.

ALso, I get the impression that Bonfire is an older CI add-on, whereas SprintPHP is new, and geared to CI version 3.0. But it seems Bonfire is still being updated. So, should an OOP / framework newbie like me go with SprintPHP or Bonfire?

Thanks.

**Comment by lonnieezell** [comment]
Testing is a huge subject that I'm not an expert in by any means. The existing tests should give you an example how to get started. Other than that, I recommend reading any tutorials on using CodeCeption or PHPUnit you can find. And then dive in. The docs for the testing part are just simply explaining the tools that Sprint uses and adds to it. 

I am writing a book on CI3. Partial chapters will be for sale in 2-3 weeks, I'm guessing. I want to finish up the current chapter, then go back through and give things a polish. That will put the book at around the 1/3 mark. While it often covers basics, it is definitely NOT a repeat of the user guide. That would be a waste of your money. Instead, it is much more the conceptual parts of using it, along with solutions and different ways to use things to make your life easier when working with CI. 

Bonfire is still valid, and Matt is doing a great job keeping it up to date. It will currently work with CI3, I believe, so it's perfect to use if you need the Admin UI already built for you. Sprint is a set of tools on top of CI3, that will be used to create a new, more robust version of Bonfire, but that hasn't happened yet. It's like a bunch of additional tools on top of CI that you can create your app from. It doesn't provide a UI but provides the tools for you to make one. So it depends on your application's needs .

**Comment by mwhitneysdsu** [comment]
There are a lot of different things to address here, but I'm only going to address the last paragraph, since I have had little chance to deal with the Sprint codebase.

I've been using and working on Bonfire for ~3 years, now. I am currently maintaining it primarily because I have one large site which uses it, and it would require a massive effort to move that site from Bonfire to any other framework, including Sprint. This means that a great deal of the work on Bonfire is done with an effort to maintain as much backwards compatibility as possible, which, in some cases, slows the project's forward progress. Even migrating from CodeIgniter 2 to 3 was a massive effort for my site, and the current state of Bonfire's support for CodeIgniter 2 and 3 reflects that (my site has been moved to CI3, so Bonfire certainly works with it, but there is still a lot of code in place to support CI2 which would not be necessary otherwise).

In the long run, though, my goal is to build a bridge for people using Bonfire to be able to migrate to Sprint (or Bonfire-Next, when that comes along), if they wish, and for the two projects to share more code. Eventually, Bonfire will use classes and interfaces defined within Sprint, though there may be some extra wrappers involved to ensure backwards compatibility, at least in the short term...

**Comment by ThinkALot** [comment]
Thanks for the info. Anyway, if anyone knows how to write tests for CI3 and SprintPHP, I hope you'll consider sharing some examples. Here's what I've figured out from reading various web sites -- and please correct me if I've gotten anything wrong:

How to make phpunit work in CI3: [Edit: This ultimately proved futile, as noted at the end of this post.]
Set up the database in acceptance.suite.yml like this
          dsn: 'mysql:host=localhost;dbname=yourDatabaseName'
          user: 'YourUserName'
          password: 'YourPassword'

In the tests folder, create a php file named ‘HelloWorldTest.php’ containing this:
    class HelloWorldTest extends \CodeIgniterTestCase
    {
        function testHelloWorld()
        {
            $this->assertTrue(true);
        }
    }

(from http://codesamplez.com/development/phpunit-tutorial-beginners)

Add this  "phpunit/phpunit": "3.7.21"  to the require-dev section in composer.json ( or  "phpunit/phpunit": "dev-master"  I guess).
Run composer update
Restart apache and mysql in Xampp.
From the project root folder, run "phpunit tests" in the CLI , where "tests" is the tests folder.
That much seems to work, although the HelloWorld test itself is not very useful.

Unfortunately, "php codecept.phar run" produces an error msg referring to a Runner.php file that does not seem to exist.

I hope someone can provide some examples that test the blog described in the tutorial, etc.

[Edit:]

I added this class to the test, and it did not produce any error, so something must be wrong:

class CITest extends CodeIgniterTestCase
  {
    private $CI;

```
public function setUp()
{
  // Load CI instance normally
  $this->CI = &get_instance();
}

public function testGetPost()
{
  $_SERVER['REQUEST_METHOD'] = 'GET';
  $_GET['foo'] = 'bar';
  $this->assertEquals('WrongValue', $this->CI->input->get_post('foo'));
}
```

  }

WrongValue should be 'bar' instead, I assume.

Modified from http://www.spidersoft.com.au/2015/phpunit-and-codeigniter-3-0/

Also, in the first class, I changed $this->assertTrue(true); to $this->assertTrue(false); but no error was reported by phpunit. 

I guess this means that phpunit is not actually working.

**Comment by lonnieezell** [comment]
I have PHPUnit installed globally through composer. Perhaps that's part of the reason? I never use the phpunit run command, honestly, but do it all through Codeception. 

Does the `tests/unit` folder have a `myth` folder in it? If you installed through Composer using --prefer-source you wouldn't have those examples. But the site's current unit tests are in the repo if you want to have a look at them. 

As an example, to run just the Sprint unit tests, I would use the following command: 

```
php codecept.phar run unit myth
```

When setting up a new test if you extend from `CodeIgniterTestCase` the `$this->ci` will already exist for you with an instance of CI. You don't need to load a CI instance. I would do your example like this: 

```
class CITest extends CodeIgniterTestCase {
    protected $ci;

    public function testGetPost()
    {
        $expected = 'bar';

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['foo'] = 'bar';
        $this->assertEquals($expected, $this->ci->input->get_post('foo'));
    }
}
```

I just copy/pasted that to a test and tried running it and it works for me both in a success and a fail condition. 

I'm running phpunit 3.7.28 here locally. Maybe that's why it's working for me? I'll have to update to the latest versions of Codeception and phpunit tonight and see if that breaks things. If you're running a newer version of phpunit, you might try updating to a newer version of CodeCeption.

**Comment by lonnieezell** [comment]
I just tried updating CodeCeption to the latest version (2.1) and the tests are still running as expected, even with the old version of phpUnit. Though, there's a bunch of date-related errors I need to fix up now... :)

EDIT: Just figured out what happened to cause the date related issues: updating to OS X 10.10.4 and it overwrote the CLI symlink to a different PHP version I had setup. So - not caused by Codeception or phpUnit.

**Comment by lonnieezell** [comment]
Whew - after fighting with dependencies for a bit, I did get the latest stable version of PHP unit installed globally through Composer - and tests are still running. You might want to check your phpUnit install, and do a `codecept.phar` self-update command to update that.

**Comment by ThinkALot** [comment]
Well, after a few attempts, I can see this is beyond me. But it's good to know that you've gotten it to work, so it is possible. I suppose you might explain the exact steps in your book. Thanks.
