### ISSUE TITLE
How do I create the first administrator ?

### ISSUE THREAD

**Issue by larbous** [ci-bonfire/Sprint#119]
I did not understand how to create the first administrator user.

**Comment by lonnieezell** [comment]
The first step would be to be to make sure you've run the FlatAuthorizationSeeder to get the default groups setup, etc. 

```
$ sprint database seed FlatAuthorizationSeeder
```

You will probably want to go through and modify the permissions that seeder is creating, since they are simply example seeds. 

You could add a $user_model->insert() within a seeder to do it, but that would require storing your password in plain text in the repo, which I would definitely recommend against. 

Instead, visit `yoursite.com/join` and create a new account. This ensures your meta info is saved and your password is hashed correctly. Then, add an entry to the `auth_groups_users` with the appropriate group and user's ids. 

Then, if you wanted to create a seeder so you could easily create it again later, you could build one that simply inserted everything into the appropriate tables, using the password hash that it generated for you.

**Comment by ronvillalon** [comment]
In case you do add $user_model->insert() with your password in plain text, there's nothing wrong with this approach but you should not set it to the password you intend to use in production. The default password should be changed immediately after Sprint setup is complete. Think of it as "hardening" your  custom version of Sprint once everything is installed and ready to go live.
