### ISSUE TITLE
Error when enabling query strings

### ISSUE THREAD

**Issue by ronvillalon** [ci-bonfire/Sprint#127]
I get the following error when I enable query strings. Any thoughts?

```
$config['enable_query_strings'] = TRUE;
```

```
Unable to determine what should be displayed. A default route has not been specified in the routing file.
```

**Comment by lonnieezell** [comment]
Why are you needing query strings enabled? This makes it so that routing works off of `?c=controller&m=index` type URI calls. Sprint is not designed to handle that. I didn't do anything specific to disable that, but I think the HMVC solution I used might be causing issues with that. 

However, that's horrible for SEO and UX anyway. :)

**Comment by ronvillalon** [comment]
Oops. You are right.. for some reason, I was thinking that would allow me to use get queries but `allow_get_array` does that. My mistake. I personally don't need it but perhaps we can close this because it really is bad for SEO.

I was using get queries for my sorting and filtering. I just found it to look much nicer and intuitive.

**Comment by lonnieezell** [comment]
I wondered, but, yeah, I use get queries for sorting and filtering all of the time. Just seems to make sense.
