### ISSUE TITLE
User registration fails with error

### ISSUE THREAD

**Issue by vinalask3** [ci-bonfire/Sprint#44]
![sprint php 2015-02-24 13-13-12](https://cloud.githubusercontent.com/assets/2475629/6349107/4a33734a-bc27-11e4-8354-96695a130dfa.png)
After a successful install and database migration, I tried to register a user account and it fails with these errors.

**Comment by ggallon** [comment]
Because in the last update of the Form Validation library and `xss_clean` (https://github.com/bcit-ci/CodeIgniter/commit/40651ebf5e29fd4a17be2cd338e8d501d41b66b1), the function `xss_clean` support removed. For more details in the commit diff itself, and here: benedmunds/CodeIgniter-Ion-Auth#683 (comment).

So, delete the `xss_clean` rule in  User_model or create your callback method [Here](http://www.codeigniter.com/userguide3/libraries/form_validation.html#callbacks-your-own-validation-methods)

**Comment by lonnieezell** [comment]
@dev-ggallon You beat me to it! :) I was thinking I had already taken that out, but that must have been in my private Bonfire repo and is probably in one of the commits I accidentally committed in this repo and had to revert yesterday. 

Good, quick catch, though!

**Comment by vinalask3** [comment]
Well done.
