### ISSUE TITLE
FlatGroupsModel::getGroupsForUser not Working as expected

### ISSUE THREAD

**Issue by vinalask3** [ci-bonfire/Sprint#47]
I created an admin-only base controller as follows:

```
class AdminController extends \Myth\Controller\ThemedController
{

    public function __construct() 
    {
        parent::__construct();
        $this->restrict();
        // Setup current_user
        $this->setupAuthClasses();
        $this->current_user = $this->authenticate->user();
        $this->restrictToGroups('admin', site_url('login'));


    }   

}
```

After creating the necessary account and activating it by changing the activation switch in the users table through phpMyadmin, I logged in and in my main controller which extends the AdminController, I did a var_dump of $this->current_user and got the following errors:

```
Error Number: 1066

Not unique table/alias: 'auth_groups'

SELECT `auth_groups_users`.*, `auth_groups`.`name`, `auth_groups`.`description` FROM `auth_groups` LEFT JOIN `auth_groups` ON `auth_groups`.`group_id` = `groups`.`id` WHERE `user_id` = 1

Filename: C:/xampp/htdocs/sites/labedesk/myth/Models/CIDbModel.php

Line Number: 480
```

I traced the error to the function referenced above and replacing the function with this solved the problem for me but I don't know if it is a robust solution so I am not sending it as a PR. Here it is:

```
public function getGroupsForUser($user_id)
    {
        $this->table_name = '';

        return $this->select('*')
                ->from('auth_groups_users')
                ->join('auth_groups', 'auth_groups_users.group_id = auth_groups.id', 'left' )
                ->where('user_id', $user_id)
                ->as_array()
                ->find_all();

    }
```

**Comment by vinalask3** [comment]
Sorry, I am not too good at this. Just an enthusiastic medic learning to code :)

**Comment by lonnieezell** [comment]
No problems, and thanks for reporting this. 

First off, you forgot to include the AuthTrait in your example. I'm assuming that's an oversight in posting here since the `restrict()` method is working for you. Just to be sure, here's how I would do an AdminController:

```
class AdminController extends \Myth\Controllers\ThemedController {

    use \Myth\Auth\AuthTrait;

    public function __construct()
    {
        parent::__construct();

        $this->restrictToGroups('admin', site_url( \Myth\Route::named('login') ));
    }

    //--------------------------------------------------------------------

}
```

By using the trait, it frees you from the other things you were doing in your example. The auth classes are automatically setup for you whenever you call one of the `restrict*()` methods so you don't need to do that manually. Also, there's no need to call both `restrict()` and `restrictToGroups()` since `restrict()` just makes sure that someone is logged in, while `restrictToGroups` makes sure that they are logged in AND belong to the proper group. So just the one call to `restrictToGroups` is needed.

You're right, though that there was an error and your fix is pretty close to what was needed to fix it. Actually, it accomplishes the same thing, but I've written mine slightly differently. I will have a fix pushed to the repo shortly. 

Guess I should step up the priority on testing the Auth\* system thoroughly. :) I'm going through writing additional tests across the system almost every day, but haven't made it to testing the Auth classes yet since that requires a bit of additional work to be able to make those tests happen in a way that covers all of the bases. 

Again, thanks for reporting this.
