### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by eincandela** [ci-bonfire/Sprint#91]
wouldn't it be possible to use "id" field in every tables? settings and user_meta are missing them.
Especially because the sprint model use them by default.

**Comment by IrcDirk** [comment]
But for what do u need it? 

U have build-in `User_model` and `Settings` library for geting data out of this tables. And those tables have indexes set on 2 colums so they dont need to have `id` fields.

**Comment by eincandela** [comment]
you are right, this is not mandatory but generaly good database design practice.

**Comment by IrcDirk** [comment]
In some cases it is not needed as u have index defined so u dont need another field. It doesnt give speed only waste of database space.

**Comment by eincandela** [comment]
i see. i know it works but I just find it useful when getting a row and updating, especially with abstract model class. it avoids to write specific where conditions + It is more "convention over configuration"

But to keep the way it is now, there should be at least 2 column unique indexes,  like for example unique (user_id, meta_key) on user_meta to avoid duplicates at database level.

**Comment by IrcDirk** [comment]
Using `User_model` u dont have to bother for getting data/updating this table "by hand".

As for indexes, there is user_id + meta_key index but its not unique, this should be fixed.

**Comment by lonnieezell** [comment]
Well, I learned something today thanks to this discussion. You can create a composite primary key that contains multiple columns. Much better than an 'id' on the table because an id column still allows you to enter duplicate information. 

In reality for user_meta - it doesn't matter since any meta with that key for that user is deleted prior to inserting the new stuff just to keep things simple. 

I'll add a 'true' to the migration to make it a primary key instead of just an index one, though and, assuming CI doesn't crash because of it, will submit that fix shortly.

Here's a [good article about it](http://weblogs.sqlteam.com/jeffs/archive/2007/08/23/composite_primary_keys.aspx).
